foreground   #c3c5dd
background   #0b0908
cursor       #c3c5dd

color0       #0b0908
color8       #88899a
color1       #6165A5
color9       #6165A5
color2       #9973A5
color10      #9973A5
color3       #C27C98
color11      #C27C98
color4       #7887BC
color12      #7887BC
color5       #9E89B4
color13      #9E89B4
color6       #DB93A8
color14      #DB93A8
color7       #c3c5dd
color15      #c3c5dd
